export const REQUEST = "REQUEST"//before request => show up window || other
export const SUCCESS = "SUCCESS"//request success => redirection || other
export const FAILURE = "FAILURE"//request fail => show up dialog || other

//ADD
export const ADD_REQUEST = "ADD_REQUEST"
export const ADD_SUCCESS = "ADD_SUCCESS"
export const ADD_FAILURE = "ADD_FAILURE"

//UPDATE
export const UPDATE_REQUEST = "UPDATE_REQUEST"
export const UPDATE_SUCCESS = "UPDATE_SUCCESS"
export const UPDATE_FAILURE = "UPDATE_FAILURE"

//前台收银；
export const POST_REQUEST = "POST_REQUEST"
export const POST_SUCCESS = "POST_SUCCESS"
export const POST_FAILURE = "POST_FAILURE"

//商品录入
export const ADDPRODUCT_REQUEST = 'ADDPRODUCT_REQUEST'
export const ADDPRODUCT_SUCCESS = 'ADDPRODUCT_SUCCESS'
export const ADDPRODUCT_FAILURE = 'ADDPRODUCT_FAILURE'

//商品浏览
export const PRODUCT_REQUEST = 'PRODUCT_REQUEST'
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE'

//商品查询
export const SEARCHPRODUCT_REQUEST = 'SEARCHPRODUCT_REQUEST'
export const SEARCHPRODUCT_SUCCESS = 'SEARCHPRODUCT_SUCCESS'
export const SEARCHPRODUCT_FAILURE = 'SEARCHPRODUCT_FAILURE'

//供应商查询
export const SUPPLIER_REQUEST = 'SUPPLIER_REQUEST'
export const SUPPLIER_SUCCESS = 'SUPPLIER_SUCCESS'
export const SUPPLIER_FAILURE = 'SUPPLIER_FAILURE'

//供应商录入
export const ADDSUPPLIER_REQUEST = 'ADDSUPPLIER_REQUEST'
export const ADDSUPPLIER_SUCCESS = 'ADDSUPPLIER_SUCCESS'
export const ADDSUPPLIER_FAILURE = 'ADDSUPPLIER_FAILURE'